// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.ConfigData>}
 */
export function GetConfig() {
    return $Call.ByID(1959981661).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetEnableAnimations() {
    return $Call.ByID(415560159);
}

/**
 * getters
 * @returns {$CancellablePromise<string>}
 */
export function GetLanguage() {
    return $Call.ByID(2658877809);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLanguages() {
    return $Call.ByID(2114410022).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetTermsAccepted() {
    return $Call.ByID(3385061523);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetTheme() {
    return $Call.ByID(973083744);
}

/**
 * @param {boolean} value
 * @returns {$CancellablePromise<void>}
 */
export function SetEnableAnimations(value) {
    return $Call.ByID(1069331283, value);
}

/**
 * setters
 * @param {string} lang
 * @returns {$CancellablePromise<void>}
 */
export function SetLanguage(lang) {
    return $Call.ByID(1329536589, lang);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetTermsAccepted() {
    return $Call.ByID(1432659951);
}

/**
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(theme) {
    return $Call.ByID(3251668900, theme);
}

// Private type creation functions
const $$createType0 = $models.ConfigData.createFrom;
const $$createType1 = $Create.Array($Create.Any);
