// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Config from "./config.js";
import * as Localization from "./localization.js";
export {
    Config,
    Localization
};

export {
    ConfigData
} from "./models.js";
