// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ConfigData {
    /**
     * Creates a new ConfigData instance.
     * @param {Partial<ConfigData>} [$$source = {}] - The source object to create the ConfigData.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigData(/** @type {Partial<ConfigData>} */($$parsedSource));
    }
}
