// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ConfigData {
    /**
     * Creates a new ConfigData instance.
     * @param {Partial<ConfigData>} [$$source = {}] - The source object to create the ConfigData.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("terms_accepted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["terms_accepted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigData(/** @type {Partial<ConfigData>} */($$parsedSource));
    }
}

export class ServerDetail {
    /**
     * Creates a new ServerDetail instance.
     * @param {Partial<ServerDetail>} [$$source = {}] - The source object to create the ServerDetail.
     */
    constructor($$source = {}) {
        if (!("players" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["players"] = 0;
        }
        if (!("admins" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["admins"] = 0;
        }
        if (!("queue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["queue"] = 0;
        }
        if (!("slots" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["slots"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerDetail(/** @type {Partial<ServerDetail>} */($$parsedSource));
    }
}
